<?php
/**
 * Functions File
 *
 * Description 
 *
 * @package    fwf
 * @version    2.0
 * @author     Fitness Website Formula
 * @link       http://fitnesswebsiteformula.com
 * @license    
 */

@ini_set( 'upload_max_size' , '64M' );
@ini_set( 'post_max_size', '64M');
@ini_set( 'max_execution_time', '300' );

/** Load the core theme framework. */
require_once( trailingslashit( get_template_directory() ) . 'library/hybrid.php' );

new Hybrid();

/** Theme setup */
function pdw_spine_theme_setup() {

	/** Custom thumbnail size */
	add_image_size('featured', 637, 280, true);
	
	add_image_size('fwf_latest_blog', 265, 150, true);

	/** Theme constants */
	define ( 'PDW_SPINE_JS_URL', trailingslashit( get_template_directory_uri() . '/js' ) );
	
	define ( 'PDW_SPINE_CSS_URL', trailingslashit( get_template_directory_uri() . '/css' ) );

	define ( 'PDW_SPINE_INC_DIR', trailingslashit( get_template_directory() . '/includes' ) );

	define ( 'PDW_SPINE_DIR', dirname( __FILE__ ) );

	define( 'PDW_SPINE_VERSION', '1.3.2' );

	/** Template tags */
	include_once PDW_SPINE_INC_DIR . 'template-tags.php';

	/** Use Foundation nav bar markup for menus */
	include_once PDW_SPINE_INC_DIR . 'navbar-walker.php';

	/** Use Foundation makrup for galleries */
	include_once PDW_SPINE_INC_DIR . 'gallery-shortcode.php';

	/** Load main stylesheet */
	add_action( 'wp_enqueue_scripts', 'pdw_spine_load_styles', 5 );

	/** Load the javascripts */
	add_action( 'wp_enqueue_scripts', 'pdw_spine_load_scripts' );
	
	/** Remove unwanted data that slow down our sites */
	remove_action( 'wp_head', array('wlb_branding', 'wlb_branding') );
	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	
	/** Hybrid Core features */
	/** Get action/filter hook prefix. */
	$prefix = hybrid_get_prefix();

	/** Add theme support for core framework features. */
	add_theme_support( 'hybrid-core-menus', array( 'primary', 'footer', 'bottom', 'members' ) );
	add_theme_support( 'hybrid-core-sidebars', array( 'primary' ) );
	add_theme_support( 'hybrid-core-widgets' );
	add_theme_support( 'hybrid-core-shortcodes' );
	add_theme_support( 'woocommerce' );

	/** Add theme settings */
	add_theme_support( 'hybrid-core-theme-settings', array( 'about', 'leadpages', 'misc', 'ultimate-offer', 'footer' ) );

	/** Include theme customizer options */
	include_once 'includes/theme-customizer.php';
	add_action( 'customize_register', 'pdw_spine_customize_register' );

	add_theme_support( 'hybrid-core-template-hierarchy' );

	/** Add theme support for framework extensions. */
	//add_theme_support( 'post-stylesheets' );
	add_theme_support( 'dev-stylesheet' );
	//add_theme_support( 'loop-pagination' );
	add_theme_support( 'get-the-image' );
	add_theme_support( 'breadcrumb-trail' );
	add_theme_support( 'cleaner-gallery' );

	/** Add theme support for WordPress features. */
	add_theme_support( 'automatic-feed-links' );
	//add_theme_support( 'post-formats', array( 'image', 'gallery' ) );

	add_theme_support( 'theme-layouts', array( '2c-l', '2c-r' ) );

	/* Add support for WordPress custom background. */
	/* add_theme_support(
		'custom-background',
		array(
			'default-color'    => '0C0B0A',
			'default-image'    => trailingslashit( get_template_directory_uri() ) . 'backgrounds/rock_wall.png',
			'wp-head-callback' => 'pdw_spine_custom_background_callback'
		)
	); */

	/* Add theme support for some included libraries. */
	add_theme_support( 'color-palette', array( 'callback' => 'pdw_spine_register_colors' ) );
	add_theme_support( 'theme-fonts',   array( 'callback' => 'pdw_spine_register_fonts', 'customizer' => true ) );

	/** Add support for WordPress custom header image. */
	/*add_theme_support(
		'custom-header',
		array(
			'wp-head-callback'    => '__return_false',
			'admin-head-callback' => '__return_false',
			'header-text'         => false,
			'default-image'       => 'remove-header',
			'width'               => 572,
			'height'              => 164
		)
	);*/

	add_theme_support( 'featured-header' );
	
	//if( hybrid_get_setting( 'extension_membership' ) ) {
		add_theme_support( 'fwf-membership' );
	//}
	
	/** Set content width. */
	hybrid_set_content_width( 637 );

	//add_filter( 'wp_nav_menu_objects',  'pdw_spine_add_parent_class'  );
	add_filter( 'wp_nav_menu_objects', 'pdw_spine_add_active_class' );

	add_filter( 'loop_pagination_args', 'pdw_spine_foundation_pagination' );

	/* Register Spine widgets. */
	add_action( 'widgets_init', 'pdw_spine_register_widgets' );
	
	/* Remove open graph images generated by yoast SEO */
	add_filter( 'wpseo_pre_analysis_post_content', 'pdw_spine_opengraph_content');
	
	function pdw_spine_opengraph_content($val) { return preg_replace("/<img[^>]+>/i", "", $val); }

	/**  custom editor styles */
	if ( is_admin() ) {
		include( 'tinymce-kit/tinymce-kit.php' );
		
		/** Load the admin javascripts && CSS */
		add_action( 'admin_enqueue_scripts', 'pdw_spine_load_admin_scripts' );
		add_action( 'admin_head', 'pdw_spine_admin_head' );
	
		/* Callback for allowing image uploads for post type 'fb_location'  */
		add_action ( 'post_edit_form_tag', 'fb_post_edit_form_tag' );
		
		function fb_post_edit_form_tag () {
			global $post;
			if ( !$post ) return;
			
			$post_type = get_post_type ( $post->ID );
			if ( $post_type != 'fb_location' ) return;
			
			printf ( ' enctype="multipart/form-data" encoding="multipart/form-data" ' );
		}
		
	} // end if

	//add_filter('post_thumbnail_html', 'pdw_spine_add_thumbnail_class',10, 3 );
	add_filter( 'get_the_image', 'pdw_spine_add_featured_img_class', 10, 1 );

	/** Register widget areas */
	add_action('widgets_init', 'pdw_spine_register_sidebars', 11);

	add_filter("{$prefix}_sidebar_defaults", 'spine_sidebar_defaults');

	add_editor_style();

	/** Jetpack feature */
	add_theme_support( 'infinite-scroll', array(
		'container'  => 'hfeed',
		'footer'     => 'page',
	) );

	/* Disable primary sidebar widgets when layout is one column. */
	add_filter( 'sidebars_widgets', 'pdw_spine_disable_sidebars' );
	add_action( 'template_redirect', 'pdw_spine_one_column' );
	
	/** Register Custom Content Types */
	if( 'slideshow' == get_theme_mod( 'theme_home_opening' ) ) {
		$custom_types = array( //[0] system [1] Singular [2] Prural [3] slug [4] capability_type [5] show_in_nav_menus [6] supports
			/*array('fb_location', 'Location', 'Locations', 'locations', 'page', TRUE, array( 'title', 'editor', 'thumbnail')),
			array('cp_promotion', 'Promotion', 'Promotions', 'promotion', 'post', FALSE, array( 'title', 'editor', 'thumbnail')),
			array('cp_event', 'Event', 'Events', 'event', 'post', FALSE, array( 'title', 'editor', 'thumbnail')),*/
			array('cp_slide', 'Slide', 'Slides', 'slide', 'post', FALSE, array( 'title', 'editor', 'thumbnail'))
		);
		
		foreach($custom_types as $type) {
			$labels = array(
			'name' => __($type[2]),
			'singular_name' => __($type[1]),
			'add_new_item' => __('Add New '. $type[1]),
			'edit_item' => __('Edit '. $type[1]),
			'new_item' => __('New '. $type[1]),
			'all_items' => __('All '. $type[2]),
			'view_item' => __('View '. $type[1]),
			'search_items' => __('Search '. $type[2]),
			'not_found' =>  __('No '. $type[3] .' found'),
			'not_found_in_trash' => __('No '. $type[3] .' found in Trash')
			);
			
			$args = array(
			'labels' => $labels,
			'public' => true,
			'show_in_nav_menus' => $type[5], 
			'show_in_menu' => TRUE,
			'capability_type' => $type[4],
			'rewrite' => array( 'slug' => $type[3], 'with_front' => FALSE ),
			'menu_position' => 20,
			'supports' => $type[6]
			);
			
			register_post_type($type[0], $args); //Create new content types
		}
	}
}

/* Do theme setup on the 'after_setup_theme' hook. */
add_action( 'after_setup_theme', 'pdw_spine_theme_setup' );

/* Load additional libraries a little later. */
add_action( 'after_setup_theme', 'pdw_spine_load_libraries', 15 );

/* Activate URL rewrites for custom content types on theme activation */
add_action( 'after_switch_theme', 'pdw_spine_rewrite_flush' );
function pdw_spine_rewrite_flush() {
    flush_rewrite_rules();
}

/* Custom Content Type Actions */
add_action( 'admin_init', 'pdw_spine_add_custom_metabox' );
add_action( 'save_post', 'pdw_spine_save_custom_postmeta' );

/**
 * Add meta box
 */
function pdw_spine_add_custom_metabox() {
	add_meta_box( 'custom-basic-info-metabox', __(  'Location Details' ), 'pdw_spine_basic_info_custom_metabox', 'fb_location', 'normal', 'high' );
	add_meta_box( 'custom-schedule-metabox', __(  'Schedule' ), 'pdw_spine_schedule_custom_metabox', 'fb_location', 'normal', 'default' );
	add_meta_box( 'custom-opening-metabox', __(  'Opening Content (FWF)' ), 'pdw_spine_opening_custom_metabox', 'page', 'normal', 'high' );
}

/**
 * Display the metaboxes
 */
function pdw_spine_basic_info_custom_metabox() {
	global $post;
	$fb_location_main_image = 	get_post_meta( $post->ID, 'fb_location_main_image', true );
	$fb_location_image2 = 		get_post_meta( $post->ID, 'fb_location_image2', true );
	$fb_location_subtitle = 	get_post_meta( $post->ID, 'fb_location_subtitle', true );
	$fb_location_street = 		get_post_meta( $post->ID, 'fb_location_street', true );
	$fb_location_city = 		get_post_meta( $post->ID, 'fb_location_city', true );
	$fb_location_state = 		get_post_meta( $post->ID, 'fb_location_state', true );
	$fb_location_country = 		get_post_meta( $post->ID, 'fb_location_country', true );
	$fb_postal_code = 			get_post_meta( $post->ID, 'fb_postal_code', true );
	$fb_location_phone = 		get_post_meta( $post->ID, 'fb_location_phone', true );
	
	$fb_location_website = 		pdw_http_url( get_post_meta( $post->ID, 'fb_location_website', true ) );
	$fb_location_signup = 		pdw_http_url( get_post_meta( $post->ID, 'fb_location_signup', true ) );
	$fb_location_facebook = 	pdw_http_url( get_post_meta( $post->ID, 'fb_location_facebook', true ) );
	$fb_location_yelp = 		pdw_http_url( get_post_meta( $post->ID, 'fb_location_yelp', true ) );
	
	$fb_location_amenities =	get_post_meta( $post->ID, 'fb_location_amenities', true );
	?>
	<h4><?php _e( 'Pictures & Address', 'fitnessthemes' ); ?></h4>
	<table class="form-table"><tbody>
	<tr valign="top"><th scope="row"><?php _e( 'Upload Primary Pictue', 'fitnessthemes' ); ?><br /><small><?php _e( 'E.g. Exterior of the building', 'fitnessthemes' ); ?></small></th>
		<td><input type="file" id="fb_location_main_image" size="100" name="fb_location_main_image" /><br /><small><?php _e( '(Larger than 600px recommended)', 'fitnessthemes' ); ?></small>
		<?php if( $fb_location_main_image ): ?><br /><img src="<?php echo $fb_location_main_image; ?>" alt="Primary location image" style="max-width:40%" /><?php endif; ?>
		</td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Upload Secondary Pictue', 'fitnessthemes' ); ?><br /><small><?php _e( 'E.g. Interior', 'fitnessthemes' ); ?></small></th>
		<td><input type="file" id="fb_location_image2" size="100" name="fb_location_image2" /><br /><small><?php _e( '(Larger than 600px recommended)', 'fitnessthemes' ); ?></small>
		<?php if( $fb_location_image2 ): ?><br /><img src="<?php echo $fb_location_image2; ?>" alt="Secondary location image" style="max-width:40%" /><?php endif; ?>
		</td></tr>
 
	<tr valign="top"><th scope="row"><?php _e( 'Location Sub-title', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_subtitle" size="70" name="fb_location_subtitle" value="<?php if( $fb_location_subtitle ) { echo $fb_location_subtitle; } ?>" /><br /><small><?php _e( '(Example: By airport)', 'fitnessthemes' ); ?></small></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Street Address', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_street" size="70" name="fb_location_street" value="<?php if( $fb_location_street ) { echo $fb_location_street; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'City', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_city" size="35" name="fb_location_city" value="<?php if( $fb_location_city ) { echo $fb_location_city; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'State/Region', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_state" size="35" name="fb_location_state" value="<?php if( $fb_location_state ) { echo $fb_location_state; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Country', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_country" size="25" name="fb_location_country" value="<?php if( $fb_location_country ) { echo $fb_location_country; } ?>" /><br /><small><?php _e( '(Helps Google Map locate your address)', 'fitnessthemes' ); ?></small></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'ZIP/Postal Code', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_postal_code" size="10" name="fb_postal_code" value="<?php if( $fb_postal_code ) { echo $fb_postal_code; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Phone', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_phone" size="25" name="fb_location_phone" value="<?php if( $fb_location_phone ) { echo $fb_location_phone; } ?>" /></td></tr>
	</table>
	<h4><?php _e( 'URLs', 'fitnessthemes' ); ?></h4>
	<table class="form-table"><tbody>
	<tr valign="top"><th scope="row"><?php _e( 'Website', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_website" size="70" name="fb_location_website" value="<?php if( $fb_location_website ) { echo $fb_location_website; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Sign Up', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_signup" size="70" name="fb_location_signup" value="<?php if( $fb_location_signup ) { echo $fb_location_signup; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Facebook', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_facebook" size="70" name="fb_location_facebook" value="<?php if( $fb_location_facebook ) { echo $fb_location_facebook; } ?>" /></td></tr>
	<tr valign="top"><th scope="row"><?php _e( 'Yelp', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_yelp" size="70" name="fb_location_yelp" value="<?php if( $fb_location_yelp ) { echo $fb_location_yelp; } ?>" /></td></tr>
	</table>
	
	<h4><?php _e( 'Other Info', 'fitnessthemes' ); ?></h4>
	<table class="form-table"><tbody>
	<tr valign="top"><th scope="row"><?php _e( 'List of Amenities', 'fitnessthemes' ); ?></th>
		<td><input type="text" id="fb_location_amenities" size="70" name="fb_location_amenities" value="<?php if( $fb_location_amenities ) { echo $fb_location_amenities; } ?>" /><br /><small><?php _e( '(Shower, changing room, kids room, etc)', 'fitnessthemes' ); ?></small></td></tr>
	<tr valign="top">
		<td colspan="2">
			<?php _e( 'Custom Content', 'fitnessthemes' ); ?>
			<?php wp_editor(
			get_post_meta( $post->ID, 'fb_location_custom_content', true ),	// Editor content.
			'fb_location_custom_content',		// Editor ID.
			array(
				'textarea_name' => 'fb_location_custom_content',
				'textarea_rows' => 4
			)
		); ?>
		<small><?php _e( 'Shortcode supported', 'fitnessthemes' ); ?></small>
		</td></tr>
	</table>
<?php
}
function pdw_spine_schedule_custom_metabox() {
	global $post;
	?>
	<table class="form-table"><tbody>
	<tr valign="top">
		<td>
			<?php _e( 'Schedule', 'fitnessthemes' ); ?>
			<?php wp_editor(
			get_post_meta( $post->ID, 'fb_location_schedule', true ),	// Editor content.
			'fb_location_schedule',		// Editor ID.
			array(
				'textarea_name' => 'fb_location_schedule',
				'textarea_rows' => 5
			)
		); ?>
		</td></tr>
	</table>
	
	<!--style type="text/css">.fb_location_schedule{width:100%;} .fb_location_schedule th {background:#cdcdcd;padding:2px;}.fb_location_schedule td{padding:2px;}</style>
	<h4><?php _e( 'Click cells to edit', 'fitnessthemes' ); ?></h4>
	<table class="fb_location_schedule" cellpadding="0" cellspacing="0">
		<tr>
			<th><?php _e( 'Mon', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Tue', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Wed', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Thu', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Fri', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Sat', 'fitnessthemes' ); ?></th>
			<th><?php _e( 'Sun', 'fitnessthemes' ); ?></th>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</table-->
	
<?php
}

function pdw_spine_opening_custom_metabox() {
	global $post;
	$fwf_page_title_bg = get_post_meta( $post->ID, 'fwf_page_title_bg', true );
	?>
	<table class="form-table"><tbody>
	<tr valign="top">
		<td>
			<?php _e( 'Opening Content', 'fitnessthemes' ); ?>
			<?php wp_editor(
			get_post_meta( $post->ID, 'sport_opening_content', true ),	// Editor content.
			'sport_opening_content',		// Editor ID.
			array(
				'textarea_name' => 'sport_opening_content',
				'textarea_rows' => 5
			)
		); ?>
		</td>
	</tr>
	<tr valign="top">
		<td><?php _e( 'Page Title Background', 'fitnessthemes' ); ?><br />
		<input type="file" id="fwf_page_title_bg" size="100" name="fwf_page_title_bg" /><br /><small><?php _e( '(Larger than 600px recommended)', 'fitnessthemes' ); ?></small>
		<?php if( $fwf_page_title_bg ): ?><br /><img src="<?php echo $fwf_page_title_bg; ?>" alt="Primary location image" style="max-width:40%" /><?php endif; ?>
		</td>
	</tr>
	</table>
<?php
}

function pdw_http_url($url) {
	return ( !preg_match( "/http(s?):\/\//", $url ) ) ? $fb_location_url = 'http://' : $url;
}

/**
 * Process the custom metabox fields for Location content type
 */
function pdw_spine_save_custom_postmeta ( $post_id ) {
	global $post;
	
	if( $post->post_type == 'page' ) {
		update_post_meta( $post_id, 'sport_opening_content', $_POST['sport_opening_content'] );
		if( !empty( $_FILES['fwf_page_title_bg']['name'] ) ) { // New image upload
			pdw_spine_insert_attachment( $post_id, 'fwf_page_title_bg' );
		}
	}
	
	if(in_array($post->post_type, array('fb_location')) && $_POST ) {
		update_post_meta( $post_id, 'fb_location_subtitle', $_POST['fb_location_subtitle'] );
		update_post_meta( $post_id, 'fb_location_street', $_POST['fb_location_street'] );
		update_post_meta( $post_id, 'fb_location_city', $_POST['fb_location_city'] );
		update_post_meta( $post_id, 'fb_location_state', $_POST['fb_location_state'] );
		update_post_meta( $post_id, 'fb_location_country', $_POST['fb_location_country'] );
		update_post_meta( $post_id, 'fb_postal_code', $_POST['fb_postal_code'] );
		update_post_meta( $post_id, 'fb_location_phone', $_POST['fb_location_phone'] );
		update_post_meta( $post_id, 'fb_location_amenities', $_POST['fb_location_amenities'] );
		update_post_meta( $post_id, 'fb_location_website', $_POST['fb_location_website'] );
		update_post_meta( $post_id, 'fb_location_signup', $_POST['fb_location_signup'] );
		update_post_meta( $post_id, 'fb_location_facebook', $_POST['fb_location_facebook'] );
		update_post_meta( $post_id, 'fb_location_yelp', $_POST['fb_location_yelp'] );
		update_post_meta( $post_id, 'fb_location_schedule', $_POST['fb_location_schedule'] );
		update_post_meta( $post_id, 'fb_location_custom_content', $_POST['fb_location_custom_content'] );
		
		if( !empty( $_FILES['fb_location_main_image']['name'] ) ) { // New image upload
			pdw_spine_insert_attachment( $post_id, 'fb_location_main_image' );
		}
		
		if( !empty( $_FILES['fb_location_image2']['name'] ) ) {
			pdw_spine_insert_attachment( $post_id, 'fb_location_image2' );
		}
	}
}

function pdw_spine_insert_attachment( $post_id, $field ) {
	require_once( ABSPATH . 'wp-admin/includes/file.php' );
	$override['action'] = 'editpost';

	$uploaded_file = wp_handle_upload($_FILES[$field], $override);

	$attachment = array(
	'post_title' => $_FILES[$field]['name'],
	'post_content' => '',
	'post_type' => 'attachment',
	'post_parent' => $post_id,
	'post_mime_type' => $_FILES[$field]['type'],
	'guid' => $uploaded_file['url']
	);
	
	// Save the data
	$id = wp_insert_attachment( $attachment,$_FILES[$field][ 'file' ], $post_id );
	wp_update_attachment_metadata( $id, wp_generate_attachment_metadata( $id, $_FILES[$field]['file'] ) );

	update_post_meta($post_id, $field, $uploaded_file['url']);
}


/**
 * Get and return the values for the URL
 */
function pdw_spine_get_url_box($pid = 0) {
	global $post;
	if($pid) {
		return get_post_meta( $pid, 'fb_location_url', true );
	} else {
		return get_post_meta( $post->ID, 'fb_location_url', true );
	}
}

/**
 * Loads some additional PHP scripts into the theme for usage.
 */
function pdw_spine_load_libraries() {
	require_once( trailingslashit( get_template_directory() ) . 'includes/color-palette.php' );
	require_once( trailingslashit( get_template_directory() ) . 'includes/theme-fonts.php' );
}

/**
 * Registers Spine extra widget areas
 */
function pdw_spine_register_sidebars(){
	register_sidebar(
		array(
			'id' => 'top_bar',
			'name' => __( 'Top Bar', 'fitnessthemes' ),
			'description' => __( 'Content inside a top bar above the header','spine' ),
			'before_widget' => '<div id="%1$s" class="fwf-top-bar row widget%2$s"><div class="columns twelve">',
			'after_widget' => '</div></div>',
			'before_title' => '',
			'after_title' => ''
		)
	);
	register_sidebar(
		array(
			'id' => 'home_top',
			'name' => __( 'Home Top Area', 'fitnessthemes' ),
			'description' => __( 'Optional widgetized area above the content','spine' ),
			'before_widget' => '<div id="%1$s" class="home_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title">',
			'after_title' => '</h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'home_bottom',
			'name' => __( 'Home Bottom Area', 'fitnessthemes' ),
			'description' => __( 'Area below the content','spine' ),
			'before_widget' => '<div id="%1$s" class="home_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title">',
			'after_title' => '</h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'lessons-sidebar',
			'name' => __( 'Lessons Sidebar Area', 'fitnessthemes' ),
			'description' => __( 'Left side menu for lessons pages','spine' ),
			'before_widget' => '<div id="%1$s" class="lessons_sidebar_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title">',
			'after_title' => '</h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'footer_left',
			'name' => __( 'Footer Area #1', 'fitnessthemes' ),
			'description' => __( 'Left widget area in the footer','spine' ),
			'before_widget' => '<div id="%1$s" class="footer_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title"><span>',
			'after_title' => '</span></h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'footer_middle',
			'name' => __( 'Footer Area #2', 'fitnessthemes' ),
			'description' => __( 'Middle widget area in the footer','spine' ),
			'before_widget' => '<div id="%1$s" class="footer_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title"><span>',
			'after_title' => '</span></h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'footer_right',
			'name' => __( 'Footer Area #3', 'fitnessthemes' ),
			'description' => __( 'Right widget area in the footer','spine' ),
			'before_widget' => '<div id="%1$s" class="footer_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title"><span>',
			'after_title' => '</span></h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'footer_bottom',
			'name' => __( 'Footer Bottom Area', 'fitnessthemes' ),
			'description' => __( 'Bottom area under the footer widgets','spine' ),
			'before_widget' => '<div id="%1$s" class="footer_bottom_widget widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title">',
			'after_title' => '</h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'footer_articles',
			'name' => __( 'Footer Area (SEO)', 'fitnessthemes' ),
			'description' => __( 'Article area in the footer','spine' ),
			'before_widget' => '<div id="%1$s" class="footer_widget_articles widget%2$s">',
			'after_widget' => '</div>',
			'before_title' => '<h5 class="widget-title">',
			'after_title' => '</h5>'
		)
	);
	register_sidebar(
		array(
			'id' => 'menu_content',
			'name' => __( 'Menu Content', 'fitnessthemes' ),
			'description' => __( 'Append content to the end of primary menu','spine' ),
			'before_widget' => '<div id="%1$s" class="menu_content">',
			'after_widget' => '</div>',
			'before_title' => '<!--',
			'after_title' => '-->'
		)
	);
	
}

function spine_sidebar_defaults($defaults){

	/* Set up some default sidebar arguments. */
	$spine = array(
		'before_widget' => '<article id="%1$s" class="panel widget %2$s widget-%2$s"><div class="widget-wrap widget-inside">',
		'after_widget'  => '</div></article>',
		'before_title'  => '<h4 class="widget-title">',
		'after_title'   => '</h4>'
	);

	array_merge( $defaults, $spine );
	return $spine;
}

/**
 * Load the necessary CSS files
 */
function pdw_spine_load_styles() {

	/* translators: If there are characters in your language that are not supported
	   by Open Sans, translate this to 'off'. Do not translate into your own language. */
	if ( 'off' !== _x( 'on', 'Open Sans font: on or off', 'spine' ) ) {
		$subsets = 'latin,latin-ext';

		/* translators: To add an additional Open Sans character subset specific to your language, translate
		   this to 'greek', 'cyrillic' or 'vietnamese'. Do not translate into your own language. */
		$subset = _x( 'no-subset', 'Open Sans font: add new subset (greek, cyrillic, vietnamese)', 'spine' );

		if ( 'cyrillic' == $subset )
			$subsets .= ',cyrillic,cyrillic-ext';
		elseif ( 'greek' == $subset )
			$subsets .= ',greek,greek-ext';
		elseif ( 'vietnamese' == $subset )
			$subsets .= ',vietnamese';

		$protocol = is_ssl() ? 'https' : 'http';
		$query_args = array(
			'family' => 'Open+Sans|ABeeZee|Oswald:400,700|Bilbo+Swash+Caps',
			'subset' => $subsets,
		);
		wp_enqueue_style( 'spine-fonts', add_query_arg( $query_args, "$protocol://fonts.googleapis.com/css" ), array(), null );
		wp_enqueue_style( 'fb-slimmenu', add_query_arg( $query_args, PDW_SPINE_CSS_URL. "slimmenu.css" ), array(), null );
	}

		/** This loads the main theme style.css */
		wp_enqueue_style( 'foundation', get_template_directory_uri(). '/css/foundation.css' );
		
		/** This loads the slideshow css */
		wp_enqueue_style( 'superslides', get_template_directory_uri(). '/css/superslides.css' );
		
		/** This loads the animation css */
		wp_enqueue_style( 'animate', get_template_directory_uri(). '/css/animate.css' );
		
		// Load Theme Settings CSS as external css file
		$admin_dir = (is_multisite()) ? site_url() . '/wp-admin/' : get_admin_url();
		wp_enqueue_style( 'theme-custom', $admin_dir . 'admin-ajax.php?action=fwf_dynamic_css', array('child-style'), $ver, $media );
		
		if( hybrid_get_setting( 'leadpages_backtoschool' ) ) {
			wp_enqueue_style( 'leadpage-b2s', get_template_directory_uri(). '/css/leadpage-school.css' );
		}
}

add_action('wp_ajax_fwf_dynamic_css', 'fwf_dynamic_css');
add_action('wp_ajax_nopriv_fwf_dynamic_css', 'fwf_dynamic_css');

function fwf_dynamic_css() {
  require_once( get_template_directory(). '/css/custom.css.php' );
  exit;
}

/**
 * Load the necessary javascript files
 */
function pdw_spine_load_scripts() {
	wp_enqueue_script( 'modernizr.foundation', PDW_SPINE_JS_URL . 'modernizr.foundation.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation', PDW_SPINE_JS_URL . 'foundation.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-buttons', PDW_SPINE_JS_URL . 'jquery.foundation.buttons.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-forms', PDW_SPINE_JS_URL . 'jquery.foundation.forms.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-mq-toggle', PDW_SPINE_JS_URL . 'jquery.foundation.mediaQueryToggle.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-navigation', PDW_SPINE_JS_URL . 'jquery.foundation.navigation.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-tabs', PDW_SPINE_JS_URL . 'jquery.foundation.tabs.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'foundation-topbar', PDW_SPINE_JS_URL . 'jquery.foundation.topbar.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	//wp_enqueue_script( 'foundation-clearing', PDW_SPINE_JS_URL . 'jquery.foundation.clearing.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-watermark', PDW_SPINE_JS_URL . 'jquery.watermark.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-simplemodal', PDW_SPINE_JS_URL . 'jquery.simplemodal.1.4.4.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-viewportchecker', PDW_SPINE_JS_URL . 'vendor/jquery.viewportchecker.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-functions', PDW_SPINE_JS_URL . 'functions.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	$resizepoint = ( $resizepoint = get_theme_mod( 'theme_slimmenu_resizewidth' ) ) ? $resizepoint : 800;
	
	wp_localize_script( 'fwf-functions', 'fwf_slimmenu_resizepoint', $resizepoint );
	
	wp_enqueue_script( 'fwf-respond', PDW_SPINE_JS_URL . 'respond.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-slimmenu', PDW_SPINE_JS_URL . 'jquery.slimmenu.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-countdown', PDW_SPINE_JS_URL . 'jquery.countdown.js', array( 'jquery' ), PDW_SPINE_VERSION, true );

	/** This is the main javascript file */
	wp_enqueue_script( 'foundation-app', PDW_SPINE_JS_URL . 'app.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
		
	/** This loads the custom theme custom.js */
	if( is_child_theme() && locate_template('custom.js') ) {
		wp_enqueue_script( 'custom-js-child', get_stylesheet_directory_uri(). '/custom.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	} else {
		wp_enqueue_script( 'custom-js', get_template_directory_uri(). '/custom.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	}
	
	/** Superslides libraries */
	wp_enqueue_script( 'slider-easing', PDW_SPINE_JS_URL . 'jquery.easing.1.3.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'slider-animate', PDW_SPINE_JS_URL . 'jquery.animate-enhanced.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'slider-superslides', PDW_SPINE_JS_URL . 'jquery.superslides.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-functions', PDW_SPINE_JS_URL . 'functions.js', array( 'jquery' ), PDW_SPINE_VERSION, true );
	
	wp_enqueue_script( 'fwf-respond', PDW_SPINE_JS_URL . 'respond.min.js', array( 'jquery' ), PDW_SPINE_VERSION, true );	
}


/* Defer parsing of JavaScript 
function pdw_spine_defer_js_parsing( $url ) {
	if ( FALSE === strpos( $url, '.js' ) ) return $url;
	if ( strpos( $url, 'jquery.js' ) ) return $url;
	return "$url' defer async='";
}
add_filter( 'clean_url', 'pdw_spine_defer_js_parsing', 11, 1 );*/
	
/* Remove Query Strings */
function pdw_spine_remove_script_version( $src ){
	$parts = explode( '?', $src );
	return $parts[0];
}
//add_filter( 'script_loader_src', 'pdw_spine_remove_script_version', 15, 1 );
//add_filter( 'style_loader_src', 'pdw_spine_remove_script_version', 15, 1 );	

/**
 * Load the necessary javascript files for admin
 */
function pdw_spine_load_admin_scripts( $hook ) {
	if ( $hook = 'appearance_page_theme-settings' ) {
		wp_enqueue_script( 'fwf-ace', PDW_SPINE_JS_URL . 'vendor/ace/ace.js', array('jquery') );
	}
	
	wp_enqueue_script( 'fwf-admin', PDW_SPINE_JS_URL . 'admin.functions.js', array('jquery') );
}

function pdw_spine_admin_head() {
	echo '<style>.modal.wpb-elements-list-modal { z-index: 99999 !important; } .modal-header .close { z-index: 2 !important; } .vc_license-activation-notice { display: none !important; }</style>';
	
	wp_enqueue_style( 'fwf-admin', get_template_directory_uri() . '/admin.css' );
}

add_filter( 'admin_body_class', 'pdw_add_admin_class', 99999 );

function pdw_add_admin_class( $classes ) {
	global $current_user;
	
	if( is_super_admin($current_user->ID) ) {
		$classes .= 'fwf-superadmin';
		
	} elseif ( array_key_exists( 'administrator', $current_user->allcaps ) ) {
		$classes .= 'fwf-admin';
		
	}
	if( array_key_exists( 'editor', $current_user->allcaps ) ) {
		$classes .= 'fwf-editor';
	
	}
	if( array_key_exists( 'subscriber', $current_user->allcaps ) ) {
		$classes .= 'fwf-subscriber';
		
	}
	
	return $classes;
}

/**
 * This is a fix for when a user sets a custom background color with no custom background image.  What
 * happens is the theme's background image hides the user-selected background color.  If a user selects a
 * background image, we'll just use the WordPress custom background callback.
 *
 * @since 0.1.0
 * @link  http://core.trac.wordpress.org/ticket/16919
 */
function pdw_spine_custom_background_callback() {

	/* Get the background image. */
	$image = get_background_image();

	/* If there's an image, just call the normal WordPress callback. We won't do anything here. */
	if ( ! empty( $image ) ) {
		_custom_background_cb();
		return;
	}

	/* Get the background color. */
	$color = get_background_color();

	/* If no background color, return. */
	if ( empty( $color ) )
		return;

	/* Use 'background' instead of 'background-color'. */
	$style = "background: #{$color};";

	?>
<style type="text/css">body.custom-background { <?php echo trim( $style ); ?> }</style>
<?php

}

/**
 * Registers custom fonts for the Theme Fonts extension.
 *
 * @since 1.0
 * @access public
 * @param  object  $theme_fonts
 * @return void
 */
function pdw_spine_register_fonts( $theme_fonts ) {

	/* Add the 'headlines' font setting. */
	$theme_fonts->add_setting(
		array(
			'id'        => 'headlines',
			'label'     => __( 'Headlines', 'fitnessthemes' ),
			'default'   => 'lato',
			'selectors' => 'h1, h2, h3, h4, h5, h6, th, .top-navbar li a, #menu-portfolio li a, .breadcrumb-trail, .page-links, .loop-pagination, .loop-nav, #respond input[type="submit"], #footer',
		)
	);
	$theme_fonts->add_setting(
		array(
			'id'        => 'body_font',
			'label'     => __( 'Body Text', 'fitnessthemes' ),
			'default'   => 'open-sans',
			'selectors' => 'body',
		)
	);

	/* Add fonts that users can select for this theme. */

	$theme_fonts->add_font(
		array(
			'handle' => 'arial',
			'label'  => __( 'Arial', 'fitnessthemes' ),
			'stack'  => 'Arial, Helvetica, sans-serif'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'trebuchet-font-stack',
			'label'  => __( 'Trebuchet (font stack)', 'fitnessthemes' ),
			'stack'  => '"Segoe UI", Candara, "Bitstream Vera Sans", "DejaVu Sans", "Bitstream Vera Sans", "Trebuchet MS", Verdana, "Verdana Ref", sans-serif'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'georgia-font-stack',
			'label'  => __( 'Georgia (font stack)', 'fitnessthemes' ),
			'stack'  => ' Constantia, "Lucida Bright", Lucidabright, "Lucida Serif", Lucida, "DejaVu Serif", "Bitstream Vera Serif", "Liberation Serif", Georgia, serif',
		)
	);

	$theme_fonts->add_font(
		array(
			'handle' => 'arvo',
			'label'  => __( 'Arvo', 'fitnessthemes' ),
			'family' => 'Arvo',
			'stack'  => 'Arvo, serif',
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'droid',
			'label'  => __( 'Droid Sans', 'fitnessthemes' ),
			'family' => 'Droid Sans',
			'stack'  => "'Droid Sans', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'exo',
			'label'  => __( 'Exo', 'fitnessthemes' ),
			'family' => 'Exo',
			'stack'  => "'Exo', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'josefin-sans',
			'label'  => __( 'Josefin Sans', 'fitnessthemes' ),
			'family' => 'Josefin Sans',
			'stack'  => "'Josefin Sans', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'lato',
			'label'  => __( 'Lato', 'fitnessthemes' ),
			'family' => 'Lato',
			'stack'  => "Lato, sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'montserrat',
			'label'  => __( 'Montserrat', 'fitnessthemes' ),
			'family' => 'Montserrat',
			'stack'  => "Montserrat, sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'muli',
			'label'  => __( 'Muli', 'fitnessthemes' ),
			'family' => 'Muli',
			'stack'  => "Muli, sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'open-sans',
			'label'  => __( 'Open Sans', 'fitnessthemes' ),
			'family' => 'Open Sans',
			'stack'  => "'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'open-sans-condensed-700',
			'label'  => __( 'Open Sans Condensed (700)', 'fitnessthemes' ),
			'family' => 'Open Sans Condensed',
			'weight' => '700',
			'stack'  => "'Open Sans Condensed', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'oswald',
			'label'  => __( 'Oswald', 'fitnessthemes' ),
			'family' => 'oswald',
			'stack'  => "'Oswald', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'pt-sans',
			'label'  => __( 'PT Sans', 'fitnessthemes' ),
			'family' => 'PT Sans',
			'stack'  => "'PT Sans', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'pt-sans',
			'label'  => __( 'PT Sans', 'fitnessthemes' ),
			'family' => 'PT Sans',
			'stack'  => "'PT Sans', sans-serif",
			'type'   => 'google'
		)
	);
	$theme_fonts->add_font(
		array(
			'handle' => 'raleway',
			'label'  => __( 'Raleway', 'fitnessthemes' ),
			'family' => 'Raleway',
			'stack'  => "'Raleway', sans-serif",
			'type'   => 'google'
		)
	);
}

/**
 * Registers colors for the Color Palette extension.
 *
 * @since 1.0
 * @access public
 * @param  object  $color_palette
 * @return void
 */
function pdw_spine_register_colors( $color_palette ) {

	/* Add custom colors. */
	/* $color_palette->add_color(
		array( 'id' => 'header_bg_color', 'label' => __( 'Header Background Color (Optional)', 'fitnessthemes' ), 'default' => '' )
	); 
	$color_palette->add_color(
		array( 'id' => 'color_scheme', 'label' => __( 'Overall Color Scheme', 'fitnessthemes' ), 'default' => '' )
	);*/
	$color_palette->add_color(
		array( 'id' => 'primary', 'label' => __( 'Primary Color', 'fitnessthemes' ), 'default' => '00aeef' )
	);
	$color_palette->add_color(
		array( 'id' => 'secondary', 'label' => __( 'Secondary Color', 'fitnessthemes' ), 'default' => '00aeef' )
	);
	$color_palette->add_color(
		array( 'id' => 'menu_primary_1', 'label' => __( 'Menu Primary #1 Color', 'fitnessthemes' ), 'default' => '00aeef' )
	);
	/*$color_palette->add_color(
		array( 'id' => 'menu_primary_2', 'label' => __( 'Menu Primary #2 Color', 'fitnessthemes' ), 'default' => '00666f' )
	);*/
	$color_palette->add_color(
		array( 'id' => 'footer_color', 'label' => __( 'Footer Text Color', 'fitnessthemes' ), 'default' => '999999' )
	);
	$color_palette->add_color(
		array( 'id' => 'tagline_color', 'label' => __( 'Header Tagline Color', 'fitnessthemes' ), 'default' => 'ffffff' )
	);
	$color_palette->add_color(
		array( 'id' => 'body_color', 'label' => __( 'Body Text Color', 'fitnessthemes' ), 'default' => '000000' )
	);

	/* Add rule sets for colors. */
	$color_palette->add_rule_set(
		'header_bg_color',
		array(
			'background-color'    => 'div.header'
		)
	);

	$color_palette->add_rule_set(
		'color_scheme',
		array(
			'background-color'    => 'footer, .nav-bar, .nav-bar > li',
			'border-color' 		  => 'hr'
		)
	);

	$color_palette->add_rule_set(
		'primary',
		array(
			'color'               => 'a, pre, code, .breadcrumb-trail a, .format-link .entry-title a .meta-nav, #respond label .required, #footer a:hover, .top-navbar .menu > li.active > a, .top-navbar .menu > li.active, .home_optin_box h4, .testimonial_container h5 .alt_color, h2.post-title, h2.entry-title a, h1.page-title, h1.entry-title a, h1.entry-title, #sidebar .widget-title, .transformations h3, .read-stories, h1.page-title, h1.loop-title, .fwf-contain h2, .fwf-contain h3, .fwf-top-scroll a:hover',
			'background-color'    => '.lessons_sidebar_widget .widget-title, .thanks-payment-info, ul.slimmenu.collapsed li, .guarantee, .social_icons a, .phone_number .icon, .address .icon, .member_login .icon, .box_center .more_info, .wod_datemeta, .top-navbar .menu > li:hover, .top-navbar li ul li a:hover, h2.post-title, .popmake input[type="submit"], .video-opt-play',
			'border-bottom-color' => '.breaadcrumb-trail a:hover, .sticky.hentry, .loop-meta, .page-template-portfolio .hentry.page, .top-navbar .menu > li.active',
			'border-top-color' => '.thanks-payment-info:after'
		)
	);

	$color_palette->add_rule_set(
		'secondary',
		array(
			'color'               => 'div[role=main] .fwf_latest_wod h4, .page-numbers.current, .transformations h3',
			'background-color'    => '.breadcrumb-trail, li.comment .comment-reply-link:hover, #footer',
			'border-top-color'    => '.hentry, .loop-meta, .attachment-meta, #comments-template, .page-template-portfolio .hentry.page',
			'border-bottom-color' => 'footer h5.widget-title'
		)
	);

	$color_palette->add_rule_set(
		'menu_primary_1',
		array(
			'color'            => '.top-navbar .menu > li.active > a, .top-navbar .menu > li.active',
			'background-color' => '#menu-primary li li a:hover, #menu-primary li li:hover > a'
		)
	);

	$color_palette->add_rule_set(
		'menu_primary_2',
		array(
			'color'               => '#menu-primary li a:hover, #menu-primary li:hover > a, #menu-primary li.current-menu-item > a',
			'background-color'    => '#menu-primary li li a',
			'border-bottom-color' => '#menu-primary-items ul li:first-child > a::after',
			'border-right-color'  => '#menu-primary-items ul ul li:first-child a::after'
		)
	);
	
	$color_palette->add_rule_set(
		'footer_color',
		array(
			'color'    => 'footer'
		)
	);
	
	$color_palette->add_rule_set(
		'tagline_color',
		array(
			'color'    => '#site-description, #site-description small'
		)
	);
	
	$color_palette->add_rule_set(
		'body_color',
		array(
			'color'    => 'body'
		)
	);
}

function pdw_spine_hasSub( $menu_item_id, $items ) {
	foreach ( $items as $item ) {
		if ( $item->menu_item_parent && $item->menu_item_parent == $menu_item_id ) {
			return true;
		}
	}
	return false;
}

/*function pdw_spine_add_parent_class( $items ) {
	foreach ( $items as $item ) {
		if ( pdw_spine_hasSub( $item->ID, $items ) ) {
			$item->classes[] = 'has-flyout'; // all elements of field "classes" of a menu item get join together and render to class attribute of <li> element in HTML
		}
	}
	return $items;
}*/

function pdw_spine_add_active_class( $items ) {
	foreach ( $items as $item ) {
		$current_element_markers = array( 'current-menu-item', 'current-menu-parent', 'current-menu-ancestor' );
		$current_class           = array_intersect( $current_element_markers, $item->classes );
		if ( ! empty( $current_class ) ) {
			$item->classes[] = 'active'; // all elements of field "classes" of a menu item get join together and render to class attribute of <li> element in HTML
		}
	}
	return $items;
}

/** Customize loop pagination extension */
function pdw_spine_foundation_pagination( $args ) {
	$args['before'] = '<div class="loop-pagination">';

	$args['type'] = 'list';

	return $args;
}

function pdw_spine_register_widgets() {
	/** Customize Nav Menu Widget */
	include_once  'includes/widget-nav-menu.php';

	/* Register the nav menu widget. */
	register_widget( 'Spine_Widget_Nav_Menu' );
}

function pdw_spine_add_featured_img_class( $img_html ) {
	/** Only do this is there's an image */
	if ( ! empty( $img_html ) )
		$img_html = '<a class="th" href="' . get_permalink( get_the_ID() ) . '" title="' . esc_attr( get_post_field( 'post_title', get_the_ID() ) ) . '">' . $img_html . '</a>';

	return $img_html;
}

function pdw_spine_fetch_bg_images() {
	$directory = PDW_SPINE_DIR . '/backgrounds/';
	//get all image files with a .jpg extension.
	$images = glob( $directory . "*.jpg" );

	return $images;
}


function pdw_spine_fetch_content_grid_classes() {

	/** Set the grid column span */
	$span_cols = apply_filters( 'spine_content_span_cols', 'twelve columns' );

		/** Layout logic  */
		if( is_singular() || is_archive() ) {	
			$layout = get_post_layout( get_the_ID() );
			
			if( $layout == 'default' && !is_page() ) {
				$layout = get_theme_mod( 'theme_layout_blog' );
			}
		}
		
		if ( empty($layout) ) {
			$layout = ( $global_layout = get_theme_mod( 'theme_layout' ) ) ? $global_layout : 'default';
		}

		//Supports new content type
		$post_type = get_post_type($post->ID);
		if( in_array($post_type, array('training-plan', 'workout', 'pmpro_series') ) )
			$layout = '1c';
		
		switch ( $layout ) {
			case 'default':
				if( is_page_template( 'templates/blog-page.php') || is_home() || ( is_home() && get_option('show_on_front') == 'posts' ) ) {
					$content_classes = "eight columns";
				} else {
					$content_classes = $span_cols;
				}
				break;
			case '1c':
				$content_classes = "twelve columns";
				break;
			case '2c-l':
				$content_classes = "eight columns";
				break;
			case '2c-r':
				$content_classes = $span_cols . " push-four";
				break;
			default:
				$content_classes = $span_cols;
				break;
		} // end switch

	return $content_classes;
}

function pdw_spine_fetch_sidebar_grid_classes() {

	$span_cols = apply_filters( 'spine_sidebar_span_cols', 'four columns' );

		/** Layout logic  */
		if( is_singular() || is_archive() ) {
			$layout = get_post_layout( get_the_ID() );
			
			if( $layout = 'default' && !is_page() ) {
				$layout = get_theme_mod( 'theme_layout_blog' );
			}
		}
		if ( empty($layout) || 'default' == $layout ) {
			$layout = get_theme_mod( 'theme_layout' );
		}
		
		switch ( $layout ) {
			case 'default' :
				$sidebar_classes = "twelve columns";
				break;
			case '1c' :
				/* Won't be displayed anyway */
				$sidebar_classes = "twelve columns";
				break;
			case '2c-l':
				$sidebar_classes = $span_cols;
				break;
			case '2c-r':
				$sidebar_classes = $span_cols . " pull-eight";
				break;
			default:
				$sidebar_classes =  "twelve columns";
				break;
		} //end switch

	return $sidebar_classes;
}

/**
 * Function for deciding which pages should have a one-column layout.
 *
 * @since 1.2.0
 */
function pdw_spine_one_column() {

	if( ( is_attachment() && 'layout-default' == theme_layouts_get_layout() ) || ( is_page() && 'layout-default' == theme_layouts_get_layout() ) ) {
		add_filter( 'get_theme_layout', 'pdw_spine_theme_layout_one_column' );
	}

}

/**
 * Filters 'get_theme_layout' by returning 'layout-1c'.
 *
 * @since 1.2.0
 * @param string $layout The layout of the current page.
 * @return string
 */
function pdw_spine_theme_layout_one_column( $layout ) {
	return 'layout-1c';
}

/**
 * Disables sidebars if viewing a one-column page.
 *
 * @since 1.2.0
 * @param array $sidebars_widgets A multidimensional array of sidebars and widgets.
 * @return array $sidebars_widgets
 */
function pdw_spine_disable_sidebars( $sidebars_widgets ) {
	global $wp_query, $wp_customize;

	if ( current_theme_supports( 'theme-layouts' ) && !is_admin() ) {
		if ( ! isset( $wp_customize ) ) {
			if ( 'layout-1c' == theme_layouts_get_layout() ) {
				$sidebars_widgets['primary'] = false;
				//$sidebars_widgets['secondary'] = false;
			}
		}
	}

	return $sidebars_widgets;
}

/**
 * Insert customizer styles to document head
 */
function pdw_spine_wp_head() {
	/* if ('fixed' == get_theme_mod( 'background_attachment' ))
	echo "<style> .pagewrap {background: transparent url(".trailingslashit( get_template_directory_uri() )."images/back-page-opacity.png) repeat;}  </style>"; */
	?>
	<?php /* <link rel="stylesheet" href="<?php echo trailingslashit( get_template_directory_uri() )?>css/font-awesome.min.css">
	<!--[if IE 7]><link rel="stylesheet" href="<?php echo trailingslashit( get_template_directory_uri() )?>css/font-awesome-ie7.min.css"><![endif]--> */ ?>
	<?php
	$container_maxwidth = get_theme_mod( 'theme_container_maxwidth' );
	
	echo "<style type=\"text/css\"> .row { max-width: {$container_maxwidth}px; }";
	
	// offset the margin top 
	if( get_theme_mod( 'fwf_logo' ) ) {
		$logo_img_id = pdw_spine_get_image_id( get_theme_mod( 'fwf_logo' ) );
		$logo_img = wp_get_attachment_image_src($logo_img_id, 'full' );
		$offset = ( $logo_img[2] - 94 ) + 115;
		echo ".opening-container { margin-top: -{$offset}px }";
	}
	echo "</style>\n\n";
	
	//Custom code for the <head> tag
	if ($misc_custom_head = hybrid_get_setting( 'misc_custom_head' )):
		echo $misc_custom_head. "\n\r";
	endif;
}
add_action( 'wp_head', 'pdw_spine_wp_head', 1 );

/**
 * Returns a set of image attachment links based on size.
 *
 * @since 0.1.0
 * @return string Links to various image sizes for the image attachment.
 */
function spine_get_image_size_links() {

	/* If not viewing an image attachment page, return. */
	if ( !wp_attachment_is_image( get_the_ID() ) )
		return;

	/* Set up an empty array for the links. */
	$links = array();

	/* Get the intermediate image sizes and add the full size to the array. */
	$sizes = get_intermediate_image_sizes();
	$sizes[] = 'full';

	/* Loop through each of the image sizes. */
	foreach ( $sizes as $size ) {

		/* Get the image source, width, height, and whether it's intermediate. */
		$image = wp_get_attachment_image_src( get_the_ID(), $size );

		/* Add the link to the array if there's an image and if $is_intermediate (4th array value) is true or full size. */
		if ( !empty( $image ) && ( true === $image[3] || 'full' == $size ) )
			$links[] = "<a class='image-size-link' href='" . esc_url( $image[0] ) . "'>{$image[1]} &times; {$image[2]}</a>";
	}

	/* Join the links in a string and return. */
	return join( ' <span class="sep">/</span> ', $links );
}

/**
 * Displays an attachment image's metadata and exif data while viewing a singular attachment page.
 *
 * Note: This function will most likely be restructured completely in the future.  The eventual plan is to
 * separate each of the elements into an attachment API that can be used across multiple themes.  Keep
 * this in mind if you plan on using the current filter hooks in this function.
 *
 * @since 0.1.0
 */
function spine_image_info() {

	/* Set up some default variables and get the image metadata. */
	$meta = wp_get_attachment_metadata( get_the_ID() );
	$items = array();
	$list = '';

	/* Add the width/height to the $items array. */
	$items['dimensions'] = sprintf( __( '<span class="prep">Dimensions:</span> %s', 'fitnessthemes' ), '<span class="image-data"><a href="' . esc_url( wp_get_attachment_url() ) . '">' . sprintf( __( '%1$s &#215; %2$s pixels', 'fitnessthemes' ), $meta['width'], $meta['height'] ) . '</a></span>' );

	/* If a timestamp exists, add it to the $items array. */
	if ( !empty( $meta['image_meta']['created_timestamp'] ) )
		$items['created_timestamp'] = sprintf( __( '<span class="prep">Date:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . date( get_option( 'date_format' ), $meta['image_meta']['created_timestamp'] ) . '</span>' );

	/* If a camera exists, add it to the $items array. */
	if ( !empty( $meta['image_meta']['camera'] ) )
		$items['camera'] = sprintf( __( '<span class="prep">Camera:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . $meta['image_meta']['camera'] . '</span>' );

	/* If an aperture exists, add it to the $items array. */
	if ( !empty( $meta['image_meta']['aperture'] ) )
		$items['aperture'] = sprintf( __( '<span class="prep">Aperture:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . sprintf( __( 'f/%s', 'fitnessthemes' ), $meta['image_meta']['aperture'] ) . '</span>' );

	/* If a focal length is set, add it to the $items array. */
	if ( !empty( $meta['image_meta']['focal_length'] ) )
		$items['focal_length'] = sprintf( __( '<span class="prep">Focal Length:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . sprintf( __( '%s mm', 'fitnessthemes' ), $meta['image_meta']['focal_length'] ) . '</span>' );

	/* If an ISO is set, add it to the $items array. */
	if ( !empty( $meta['image_meta']['iso'] ) )
		$items['iso'] = sprintf( __( '<span class="prep">ISO:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . $meta['image_meta']['iso'] . '</span>' );

	/* If a shutter speed is given, format the float into a fraction and add it to the $items array. */
	if ( !empty( $meta['image_meta']['shutter_speed'] ) ) {

		if ( ( 1 / $meta['image_meta']['shutter_speed'] ) > 1 ) {
			$shutter_speed = '1/';

			if ( number_format( ( 1 / $meta['image_meta']['shutter_speed'] ), 1 ) ==  number_format( ( 1 / $meta['image_meta']['shutter_speed'] ), 0 ) )
				$shutter_speed .= number_format( ( 1 / $meta['image_meta']['shutter_speed'] ), 0, '.', '' );
			else
				$shutter_speed .= number_format( ( 1 / $meta['image_meta']['shutter_speed'] ), 1, '.', '' );
		} else {
			$shutter_speed = $meta['image_meta']['shutter_speed'];
		}

		$items['shutter_speed'] = sprintf( __( '<span class="prep">Shutter Speed:</span> %s', 'fitnessthemes' ), '<span class="image-data">' . sprintf( __( '%s sec', 'fitnessthemes' ), $shutter_speed ) . '</span>' );
	}

	/* Allow devs to overwrite the array of items. */
	$items = apply_atomic( 'image_info_items', $items );

	/* Loop through the items, wrapping each in an <li> element. */
	foreach ( $items as $item )
		$list .= "<li>{$item}</li>";

	/* Format the HTML output of the function. */
	$output = '<div class="image-info"><h3>' . __( 'Image Info', 'picturesque' ) . '</h3><ul>' . $list . '</ul></div>';

	/* Display the image info and allow devs to overwrite the final output. */
	echo apply_atomic( 'image_info', $output );
}


add_filter('wp_get_attachment_image_attributes','pdw_spine_attachment_attrs',10,2);
function pdw_spine_attachment_attrs($attr, $attachment ){
	$attr['data-caption'] = $attachment->post_title;
	return $attr;
}

//temporary shortcoder
function spine_shortcoder( $content ) {
	$content = str_replace('[GUARANTEE]', '<script>document.write(\' '. addslashes(hybrid_get_setting('uo_guarantee_copy')) .' \')</script>', $content);
	
	$content = str_replace('[sectionbox]', '<div class="sectionbox">', $content);
	$content = str_replace('[/sectionbox]', '</div>', $content);
	$content = str_replace('[johnsonbox_feature]', '<div class="johnsonbox_feature">', $content);
	$content = str_replace('[/johnsonbox_feature]', '</div>', $content);
	
	$content = str_replace('[MY_CITY]', hybrid_get_setting('uo_my_city'), $content);
	$content = str_replace('[MY_STATE]', hybrid_get_setting('uo_my_state'), $content);
	$content = str_replace('[YEAR]', hybrid_get_setting('uo_year'), $content);
	$content = str_replace('[MY_NAME]', hybrid_get_setting('uo_my_name'), $content);
	$content = str_replace('[BUSINESS_NAME]', hybrid_get_setting('uo_business_name'), $content);
	$content = str_replace('[PHONE_NUMBER]', hybrid_get_setting('uo_phone_number'), $content);
	$content = str_replace('[LIST_OF_CITIES]', hybrid_get_setting('uo_list_of_cities'), $content);
	$content = str_replace('[LIST_OF_ZIPCODES]', hybrid_get_setting('uo_list_of_zipcodes'), $content);
	$content = str_replace('[SIGN_UP_BUTTON]', hybrid_get_setting('uo_sign_up_button'), $content);
	
	return $content;
}
add_filter('the_content', 'spine_shortcoder', 10);

/*
* Add page title on/off option for Sales site only and Combo type
*/
add_action('add_meta_boxes', 'spine_pagetitle_box');
add_action('save_post', 'spine_pagetitle_save');

function spine_pagetitle_box() {
    add_meta_box( 
        'spine_page_title',
        __('Theme Options', 'topblogformula'),
        'spine_pagetitle_inner_custom_box',
        'page',
		'side',
		'default'
    );
}
function spine_pagetitle_inner_custom_box($post) {
  // Use nonce for verification
  wp_nonce_field('spine_action', 'spine_pagemeta');

  // The actual fields for data entry
  echo '<label for="spine_pagetitle_field">';
       _e("Disable page title", 'fitnessthemes' );
  echo '</label> ';
  echo '<input type="checkbox" id="spine_pagetitle_field" name="spine_pagetitle_field" value="1" '.((is_pageTitleHidden() === true) ? 'checked="checked"' : '').' /><br />';
  
  echo '<label for="spine_pagenav_field">';
       _e("Disable nav menu", 'fitnessthemes' );
  echo '</label> ';
  echo '<input type="checkbox" id="spine_pagenav_field" name="spine_pagenav_field" value="1" '.((is_pageNavHidden() === true) ? 'checked="checked"' : '').' /><br />';
  
   echo '<label for="spine_videooptin_field">';
       _e("Disable Ultimate Offer", 'fitnessthemes' );
  echo '</label> ';
  echo '<input type="checkbox" id="spine_videooptin_field" name="spine_videooptin_field" value="1" '.((is_pageUltimateOfferHidden() === true) ? 'checked="checked"' : '').' /><br />';
}

function spine_pagetitle_save($post_id) {
  //Make sure it's not saved by auto save routine
  if ( defined('DOING_AUTOSAVE') && DOING_AUTOSAVE || empty($post_id) ) 
    return $post_id;

  // verify this came from the our screen and with proper authorization,
  if (!wp_verify_nonce($_POST['spine_pagemeta'], 'spine_action'))
      return;
	  
  //Check permissions
  if ($_POST['post_type'] == 'page') {
    if (!current_user_can('edit_page', $post_id))
      return $post_id;
  } else {
    if (!current_user_can('edit_post', $post_id))
      return $post_id;
  }
  //Authentication done - Save the data
	if(isset($_POST['spine_pagetitle_field'])) {
	  $pagetitle = intval($_POST['spine_pagetitle_field']);
	  if($pagetitle == 1) {
		update_post_meta($post_id,'_hide_pagetitle','1');
	  } else {
		delete_post_meta($post_id, '_hide_pagetitle');
	  }
	}
	if(isset($_POST['spine_pagenav_field'])) {
	  $pagenav = intval($_POST['spine_pagenav_field']);
	  if($pagenav == 1) {
		update_post_meta($post_id,'_hide_pagenav','1');
	  } else {
		delete_post_meta($post_id, '_hide_pagenav');
	  }
	}
	if(isset($_POST['spine_videooptin_field'])) {
	  $pagenav = intval($_POST['spine_videooptin_field']);
	  if($pagenav == 1) {
		update_post_meta($post_id,'_hide_UltimateOffer','1');
	  } else {
		delete_post_meta($post_id, '_hide_UltimateOffer');
	  }
	}  
}
/*
* Check to see if page tile is disabled
*/ 
function is_pageTitleHidden() {
	global $post;
	$post_id = ( is_home() && get_option('page_for_posts') ) ? get_option('page_for_posts') : $post->ID;
	
	if(get_post_meta($post_id, '_hide_pagetitle', true) == 1) {
		return true;
	} else {
		return false;
	}
}
/*
* Check to see if navigation menu is disabled
*/ 
function is_pageNavHidden() {
	global $post;
	if(get_post_meta($post->ID, '_hide_pagenav', true) == 1) {
		return true;
	} else {
		return false;
	}
}
/*
* Check to see if Ultimate Offer Boxes are disabled
*/ 
function is_pageUltimateOfferHidden() {
	global $post;
	if(get_post_meta($post->ID, '_hide_UltimateOffer', true) == 1) {
		return true;
	} else {
		return false;
	}
}

function spine_wp_footer() {
	?><div id="modal_offer_box"><?php echo hybrid_get_setting('uo_trial_offer_box');
	if ($uo_trial_offer_formhtml = hybrid_get_setting('uo_trial_offer_formhtml'))
		echo $uo_trial_offer_formhtml;
	else
		$consultform = do_shortcode( hybrid_get_setting('uo_trial_offer_shortcode') ); echo preg_replace(array('/\r/', '/\n/'), '', $consultform); 
	echo '</div>'; ?>
<script>
	<?php if( get_theme_mod( 'theme_shrink_header' ) ) { ?>jQuery(document).on("scroll", function(){
	if( jQuery(document).scrollTop() > 80 ) { 
		jQuery(".shadow").addClass("fwf-shrink"); } else { 
		jQuery(".shadow").removeClass("fwf-shrink"); 
	}
	});
	<?php } ?>
	jQuery(document).ready(function($) { $(document).foundation(); });
</script><?php

	//Custom code before <body> tag
	if ($misc_custom_footer = hybrid_get_setting( 'misc_custom_footer' )):
		echo $misc_custom_footer. "\n\r";
	endif;
}
add_action('wp_footer', 'spine_wp_footer', 99);

/*
/* Hook to add custom content immediately after <body>
*/
if ( !function_exists( 'fb_before_body' ) ) {
	function fb_before_body() {
		do_action('fb_before_body');
	}
}

function pdw_spine_social_icons() {
	global $post;
	$url_facebook = get_theme_mod('theme_url_facebook');
	$url_twitter = get_theme_mod('theme_url_twitter');
	$url_youtube = get_theme_mod('theme_url_youtube');
	$url_yelp = get_theme_mod('theme_url_yelp');
	$url_instagram = get_theme_mod('theme_url_instagram');
	$url_googleplus = get_theme_mod('theme_url_googleplus');
?>
	<?php if ($url_facebook && $url_facebook != 'http://'):?><span class="facebook"><a href="<?php echo $url_facebook; ?>" rel="me" target="_blank">Facebook</a></span><?php endif; ?>
	<?php if ($url_twitter && $url_twitter != 'http://'):?><span class="twitter"><a href="<?php echo $url_twitter; ?>" rel="me" target="_blank">Twitter</a></span><?php endif; ?>
	<?php if ($url_youtube && $url_youtube != 'http://'):?><span class="youtube"><a href="<?php echo $url_youtube; ?>" rel="me" target="_blank">YouTube</a></span><?php endif; ?>
	<?php if ($url_instagram && $url_instagram != 'http://'):?><span class="instagram"><a href="<?php echo $url_instagram; ?>" rel="me" target="_blank">Instagram</a></span><?php endif; ?>
	<?php if ($url_googleplus && $url_googleplus != 'http://'):?><span class="googleplus"><a href="<?php echo $url_googleplus; ?>" rel="Publisher" target="_blank">Google+</a></span><?php endif; ?>
	<?php if ($url_yelp && $url_yelp != 'http://'):?><span class="yelp"><a href="<?php echo $url_yelp; ?>" rel="me" target="_blank">Yelp</a></span><?php endif; ?>
<?php
}
add_action( 'fwf_social_icons', 'pdw_spine_social_icons' );

function pdw_spine_head() {
}
add_action( 'fwf_head', 'pdw_spine_head' );

function pdw_spine_ultimate_offer() { ?>
<div class="twelve columns">
	<?php
	$uo_video = hybrid_get_setting( 'uo_video_home' );
	$uo_optin = hybrid_get_setting( 'uo_trial_offer_box_home' );
	?>
	<?php echo ($uo_video && $uo_optin) ? '<div class="four_half columns uo_video">'. $uo_video. '</div>' : ($uo_video ? '<div class="row uo_video">'. $uo_video. '</div>' : ''); ?>
	
	<?php echo ($uo_video && $uo_optin) ? '<div class="seven_half columns uo_optin">'. $uo_optin. '</div>' : ($uo_optin ? '<div class="row uo_optin">'. $uo_optin. '</div>' : ''); ?>
</div>
<?php 
}
add_action( 'fwf_ultimate_offer', 'pdw_spine_ultimate_offer' );

/* SuperSlider Slideshow */
function pdw_spine_superslider() {

	$args = array( 'post_type' => 'cp_slide', 'posts_per_page' => 10 );
	$loop = new WP_Query( $args );
	//$cnt = 1;
	
	//If no slide is found
	if( !$loop->found_posts ) {
		if( is_front_page() ) {
			echo '<div class="no_slideshow">';
			do_action( 'fwf_before_pagestarts' ); 
			echo '</div>';
		}	
		return;
	}
	?>
<script>
jQuery(function() {
  jQuery('#slides').superslides({
	inherit_width_from: '.wide-container',
	inherit_height_from: '.wide-container',
	animation: 'fade',
	play: 9000	
  });
});
</script>
<div class="slideshow wide-container">
    <div id="slides">
      <ul class="slides-container">
	<?php while ( $loop->have_posts() ) : $loop->the_post(); ?>
        <li>
			<?php //the_post_thumbnail( 'full' ); ?>
			<?php $img_meta = wp_get_attachment_image_src( get_post_thumbnail_id( $loop->ID ), 'full' , false );?>
			<div class="slide-image" style="background-image: url(<?php echo $img_meta[0]; ?>);"></div>
			<div class="slide-container">
				<?php the_content(); ?>
			</div>
        </li>
	<?php endwhile; ?>
      <?php /*<nav class="slides-navigation">
        <a href="#" class="next">Next</a>
        <a href="#" class="prev">Previous</a>
      </nav> */ ?>
    </div>
	
</div>
<?php
}
add_action( 'fwf_slideshow', 'pdw_spine_superslider' );

function the_excerpt_max_charlength($charlength) {
	$excerpt = get_the_excerpt();
	$charlength++;

	if ( mb_strlen( $excerpt ) > $charlength ) {
		$subex = mb_substr( $excerpt, 0, $charlength - 5 );
		$exwords = explode( ' ', $subex );
		$excut = - ( mb_strlen( $exwords[ count( $exwords ) - 1 ] ) );
		if ( $excut < 0 ) {
			$excerpt = mb_substr( $subex, 0, $excut );
		} else {
			$excerpt = $subex;
		}
		return $excerpt. '<a href="'. get_permalink() .'">[...]</a>';
	} else {
		return $excerpt;
	}
}
function new_excerpt_more( $more ) {
	return ' <a class="read-more" href="'. get_permalink( get_the_ID() ) . '">[...]</a>';
}
add_filter( 'excerpt_more', 'new_excerpt_more' );

add_action( 'fwf_before_pagestarts', 'pdw_spine_opening_content');

function pdw_spine_opening_content() {
	global $post;
	
	if( $opening_content = get_post_meta( $post->ID, 'sport_opening_content', true ) ) {
		echo '<div class="opening_content">' . $opening_content . '</div>';
	}
}

function fwf_has_container() {
	global $post;
	
	$fullwidth_layouts = array( 'templates/layout-3.php', 'templates/layout-4.php', 'templates/layout-lessons-page.php' );
	
	$template_slug = get_page_template_slug( $post->ID );
	
	if( !is_page_template('templates/home-page.php') && ( !in_array( $template_slug, $fullwidth_layouts ) ) && !in_array($post->post_type, array('training-plan', 'pmpro_series' ) ) ) {
		return '<div class="row pagewrap">' . "\n";
	}
}

function fwf_has_header_footer() {
	global $post;
	
	$no_header_footer = array( 'templates/layout-2.php', 'templates/layout-5.php' );
	
	$template_slug = get_page_template_slug( $post->ID );
	
	if( ( !in_array( $template_slug, $no_header_footer ) ) ) {
		return true;
	}
}

function fwf_widget_shortcode($atts) {
    
    global $wp_widget_factory;
    
    extract(shortcode_atts(array(
        'name' => FALSE,
        'title' => ''
    ), $atts));
    
    $name = wp_specialchars($name);
    
    if (!is_a($wp_widget_factory->widgets[$name], 'WP_Widget')):
        $wp_class = 'WP_Widget_'.ucwords(strtolower($class));
        
        if (!is_a($wp_widget_factory->widgets[$wp_class], 'WP_Widget')):
            return '<p>'.sprintf(__("%s: Widget class not found. Make sure this widget exists and the class name is correct"),'<strong>'.$class.'</strong>').'</p>';
        else:
            $class = $wp_class;
        endif;
    endif;
    
    ob_start();
    the_widget($name, $instance, array('widget_id'=>'arbitrary-instance-'.$id,
        'before_widget' => '',
        'after_widget' => '',
        'before_title' => '',
        'after_title' => ''
    ));
    $output = ob_get_contents();
    ob_end_clean();
    
    if( $title ) {
	$output = str_replace( '<h4></h4>', '<h4>' . $title . '</h4>', $output );
    }
    
    return $output;
    
}
add_shortcode('fwf_widget_shortcode','fwf_widget_shortcode'); 

// retrieves the attachment ID from the file URL
function pdw_spine_get_image_id( $image_url ) {
	global $wpdb;
	$attachment = $wpdb->get_col( $wpdb->prepare( "SELECT ID FROM $wpdb->posts WHERE guid='%s';", $image_url ) );
	return $attachment[0]; 
}

/*
 * Back up/restore theme option
 */
class pdw_spine_backup_restore_theme_settings {

	function pdw_spine_backup_restore_theme_settings() {
		add_action( 'admin_menu', array(&$this, 'admin_menu') );
	}
	
	function admin_menu() {
		$page = add_theme_page( 'Backup/Restore', 'Backup/Restore', 'manage_options', 'backup-settings', array(&$this, 'options_page') );

		add_action( "load-{$page}", array(&$this, 'import_export') );
	}
	
	function import_export() {
		if ( isset( $_GET['action'] ) && ( $_GET['action'] == 'download' ) ) {
			
			$blog_info = get_blog_details( $GLOBALS['blog_id'] );
			$blog_directory = str_replace( '/', '', $blog_info->path );
			
			header( "Cache-Control: public, must-revalidate" );
			header( "Pragma: hack" );
			header( "Content-Type: text/plain" );
			header( 'Content-Disposition: attachment; filename="'. $blog_directory. '-theme-settings-'. date("Y-m-d"). '.dat"' );
			echo serialize( $this->_get_settings() );
			die();
		}
		
		if ( isset($_POST['upload']) && check_admin_referer( 'fwf_restoreSettings', 'fwf_restoreSettings') ) {
			if ( $_FILES["file"]["error"] > 0 ) {
				// error
			} else {
				$settings = unserialize( file_get_contents( $_FILES["file"]["tmp_name"] ) );
				if ( $settings ) {
					foreach ( $settings as $setting ) {
						update_option( $setting->option_name, unserialize($setting->option_value) );
					}
				}
			}
			wp_redirect( admin_url( 'themes.php?page=backup-settings') );
			exit;
		}
	}
	function options_page() { ?>

		<div class="wrap">
			<?php screen_icon(); ?>
			<h2>Backup/Restore Theme Settings</h2>
			<form action="" method="POST" enctype="multipart/form-data">
				<style>#backup-settings td { display: block; margin-bottom: 20px; }</style>
				<table id="backup-settings">
					<tr>
						<td>
							<h3>Backup/Export</h3>
							<p>Here are the stored settings for the current theme:</p>
							<p><textarea class="widefat code" rows="10" cols="100" onclick="this.select()" style="font-size:12px;"><?php echo serialize($this->_get_settings()); ?></textarea></p>
							<p><a href="?page=backup-settings&action=download" class="button-secondary">Download as file</a></p>
						</td>
						<td>
							<h3>Restore/Import</h3>
							<p><label class="description" for="upload">Restore a previous backup</label></p>
							<p><input type="file" name="file" /> <input type="submit" name="upload" id="upload" class="button-primary" value="Upload file" /></p>
							<?php if (function_exists('wp_nonce_field')) wp_nonce_field('fwf_restoreSettings', 'fwf_restoreSettings'); ?>
						</td>
					</tr>
				</table>
			</form>
		</div>

	<?php }
	/*function _display_settings() {
		$settings = unserialize($this->_get_settings());
	}*/
	function _get_settings() {
		global $wpdb;
		return $wpdb->get_results("SELECT option_name, option_value FROM {$wpdb->options} WHERE option_name = 'fwf_theme_settings'");
	}
}

new pdw_spine_backup_restore_theme_settings();

add_filter( 'the_content', 'sc_replacecolon', 5 );
function sc_replacecolon( $content ){ return str_replace( '[sc:', '[sc name=', $content ); }

add_filter( 'body_class','fwf_body_classes' );
function fwf_body_classes( $classes ) {
	global $current_user;

	if( $post->post_type == 'pmpro_series' ) {
		$classes[] = 'page-template-layout-3';
	}
	
	if( is_user_logged_in() && isset($current_user->roles) && in_array( 'subscriber', $current_user->roles ) ) {
		$classes[] = 'role-subscriber';

			if( function_exists( 'pmpro_getMembershipLevelsForUser' ) ) {
				if( pmpro_getMembershipLevelsForUser( $current_user->ID ) ) {
					
					//Also remove wp bar for end users
					add_filter('show_admin_bar', '__return_false');
				}
			}
	}
	
	return $classes;
}

add_shortcode('global_proceed_to_profile','fwf_to_profile_shortcode'); 
function fwf_to_profile_shortcode($atts) {
    
    extract(shortcode_atts(array(
        'html' => ''
    ), $atts));

    return $html . '<h2>You\'re almost finished!</h2>
<a class="button btn uk-button uk-button-primary uk-button-large" href="'. site_url( '/nutrition-profile/', 'https' ) .'"><strong class="uk-text-large">Click Here to Complete your Profile</strong></a>';
    
}


add_filter('script_loader_tag', 'add_async_attribute', 10, 2);
function add_async_attribute($tag, $handle) {
    if ( 'vide' !== $handle )
        return $tag;
    return str_replace( ' src', ' data-pagespeed-no-defer src', $tag );
}


/////////// Sub-site Exceptions ////////////
add_action( 'template_redirect', 'fwf_process_user' );
function fwf_process_user() {
	global $current_user;
	
	//Client users on Joey's site
	if( get_current_blog_id() == 24 && in_array('subscriber', $current_user->roles) ) {
		if( !is_network_admin($current_user->ID) && is_front_page() ) {
			wp_redirect(site_url('members-dashboard'));
			exit();
		}
	}
}

function fwf_getHeaderCols() {
	$header_layout = get_theme_mod('theme_layout_header');

	switch ($header_layout) {
		case 'half':
			$cols['left'] = 'six';
			$cols['right'] = 'six';
			return $cols;
			break;
		
		case 'one-fourth':
			$cols['left'] = 'three';
			$cols['right'] = 'nine';
			return $cols;
			break;

		default:
			$cols['left'] = 'four';
			$cols['right'] = 'eight';
			return $cols;
			break;
	}
}

remove_filter('widget_text_content', 'wpautop');


add_action('fb_after_body', 'fwf_install_gtm_body');
add_action('fb_gtm_header', 'fwf_install_gtm_header');

function fwf_install_gtm_body() {
	if ($misc_gtm_tag = hybrid_get_setting( 'misc_gtm_tag' )): ?>
	<!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $misc_gtm_tag; ?>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->
	<?php
	endif;
}

function fwf_install_gtm_header() {
	if ($misc_gtm_tag = hybrid_get_setting( 'misc_gtm_tag' )): ?>
	<!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','<?php echo $misc_gtm_tag; ?>');</script>
	<!-- End Google Tag Manager -->
	<?php
	endif;
}

/* Remove Remove query strings from static resources */
function _remove_query_strings_1( $src ){	
	$rqs = explode( '?ver', $src );
        return $rqs[0];
}

function _remove_query_strings_2( $src ){
	$rqs = explode( '&ver', $src );
        return $rqs[0];
}

if ( !is_admin() ) {
	add_filter( 'script_loader_src', '_remove_query_strings_1', 15, 1 );
	add_filter( 'style_loader_src', '_remove_query_strings_1', 15, 1 );
	add_filter( 'script_loader_src', '_remove_query_strings_2', 15, 1 );
	add_filter( 'style_loader_src', '_remove_query_strings_2', 15, 1 );
}

function fwf_login_page_css() { ?>
    <style type="text/css">
        <?php echo hybrid_get_setting('misc_custom_css'); 
        
        // Replace WordPress logo
		if( get_theme_mod( 'fwf_logo' ) ) {
			$logo_img_id = pdw_spine_get_image_id( get_theme_mod( 'fwf_logo' ) );
			$logo_img = wp_get_attachment_image_src($logo_img_id, 'full' );
			if($logo_img) {
			echo ".login #login h1 a { background-size: initial; background-image: url(" . str_replace('http://', '//', $logo_img[0]) . "); height: {$logo_img[2]}px; width: {$logo_img[1]}px; }";
			}
		}

        ?>
    </style>
<?php }
add_action( 'login_enqueue_scripts', 'fwf_login_page_css' );

add_shortcode('fwf_user_first_name','fwf_user_first_name'); 

function fwf_user_first_name() {
	global $current_user;

	return get_user_meta($current_user->ID, 'first_name', true);
}

// changing the logo link from wordpress.org to our site
function fwf_login_url() {  return home_url(); }
add_filter( 'login_headerurl', 'fwf_login_url' );

// changing the alt text on the logo to show client site name
function fwf_login_title() { return get_option( 'blogname' ); }
add_filter( 'login_headertitle', 'fwf_login_title' );

//New! Custom widget area at the end of menu
add_filter('wp_nav_menu_items', 'fwf_menu_extra_content', 10, 2); 
function fwf_menu_extra_content($items, $args) { 
        ob_start(); 
        if (!dynamic_sidebar( 'Menu Content' )): 
        endif;
        $menu_content = ob_get_contents(); 
        ob_end_clean();   
        $items .= '<li>'. $menu_content .'</li>';     
        return $items; 
}
